safe: true
lsi: false
pygments: true
permalink: /posts/:title
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

name: Corey Haines
url: http://articles.coreyhaines.com
description: Corey's Ramblings
twitter: coreyhaines
github: coreyhaines
gravatar_url: http://www.gravatar.com/avatar/3d7807bb66e1a0c68c73ab2daaa77d8f
